workspace: /Users/marcostagni/Documents/dev/personal/Mage-Workspace
project: newprojectmarco21
scene: Marco
electron:
  window:
    title: Mage Studio
    darkTheme: true
template:
  projectUrl: >-
    https://s3.us-east-2.amazonaws.com/mage.studio.test-bucket/project.template.tgz
  sceneUrl: >-
    https://s3.us-east-2.amazonaws.com/mage.studio.test-bucket/scene.template.tgz
